### ISSUE TITLE
Clojure solutions (until day 15 as of now)

### ISSUE THREAD

**Issue by jabberabbe** [massimo-zaniboni/aoc-benchmarks#3]
This is the link to all the solutions I wrote for this year in Clojure: [jabberabbe/advent-of-code](https://github.com/jabberabbe/advent-of-code/tree/master/2021). Every problem is split into two separate independent files (part A and part B).
Each script takes the program input on stdin and writes the solution to stdout.
Some notes:

- Leave out days 05 and 08 (they're example of bad coding practice; I will try to find some time to write them again from scratch).
- Day 13 requires input preprocessing (at the moment). Feel free to leave it out; I put a short comment at the top of the file with some Ex-commands to create the required format. I will add some lines of code to parse the original input format.
- Assuming you have already installed Clojure you can run the scripts from the shell with the following command: `clj -M [clojure_file_containing_solution] < [input_file]`. Keep the file `deps.edn` in the same directory of the scripts and run `clj` from that directory.
- Alternatively, solutions that do not depend on external libraries (all except Day 15) can be run with the [Babashka](https://github.com/babashka/babashka) Clojure runtime, which uses GraalVM and has a much faster startup time (JVM clojure takes about 4s to start on my 2016 MacBook Pro). However, on big inputs the JVM may perform much better (we'll see). Assuming Babashka is installed: `bb -f [clojure_file_containing_solution] < [input_file]`.

Thank you!

**Comment by massimo-zaniboni** [comment]
Devo ancora sistemare delle cose (manca la map) e verificarne delle altre, ma si inizia a vedere qualcosa.

Ho messo un timeout a 15m (prima era a 1h), ma penso che se non esegue entro 15m poi non esegue neanche dopo 1h. Almeno Babashka faceva cosī.

**Comment by massimo-zaniboni** [comment]
@jabberabbe sul 15b anche esenguendolo nel modo che mi hai detto ottengo questo errore

```
clj -M 15b.clj < ../aoc2021-day15b-input1.txt 
Syntax error (IllegalArgumentException) compiling recur at (15b.clj:56:9).
Mismatched argument count to recur, expected: 2 args, got: 3

Full report at:
/tmp/clojure-10336981205836825015.edn
```

**Comment by jabberabbe** [comment]
Fixed, avevo modificato il 15a e poi non avevo fiato una cosa nel 15b.
In ogni caso su big boys potrebbe richiedere moltissimo, ho implementato Dijkstra e devo riempire l'intera queue nodo per nodo. Mi ero riproposto di riscriverlo inizializzando la queue come vuota e poi aggiungendo i nodi visitati, o qualcosa del genere, per evitare di dover creare una struttura dati enorme ancora prima di eseguire l'algoritmo.

**Comment by massimo-zaniboni** [comment]
DONE
